"""Pattern knowledge base: dangerous sinks, untrusted sources, entrypoints, path signals.

Every rule is deliberately cheap (one regex) because the point is triage: rank where a human
or an LLM should look first, not prove exploitability. Weight is "how much this raises my
eyebrow", 1-10. Categories carry the CWE so a report can cite something real.
"""
from __future__ import annotations

import re

# ---------------------------------------------------------------- categories

CATEGORIES = {
    "cmd":      {"name": "OS Command Injection",       "cwe": "CWE-78",   "accent": "#ff5f56"},
    "code":     {"name": "Code / Expression Injection", "cwe": "CWE-94",  "accent": "#ff7b45"},
    "sqli":     {"name": "SQL Injection",              "cwe": "CWE-89",   "accent": "#ff9500"},
    "nosql":    {"name": "NoSQL / Query Injection",    "cwe": "CWE-943",  "accent": "#ffb454"},
    "deser":    {"name": "Insecure Deserialization",   "cwe": "CWE-502",  "accent": "#ff4d8d"},
    "path":     {"name": "Path Traversal / File Access", "cwe": "CWE-22", "accent": "#d68cff"},
    "upload":   {"name": "Unrestricted Upload",        "cwe": "CWE-434",  "accent": "#b07cff"},
    "ssrf":     {"name": "SSRF / Outbound Fetch",      "cwe": "CWE-918",  "accent": "#5ac8fa"},
    "xss":      {"name": "XSS / Unsafe HTML Sink",     "cwe": "CWE-79",   "accent": "#64d2ff"},
    "tmpl":     {"name": "Template Injection",         "cwe": "CWE-1336", "accent": "#7fd1ae"},
    "xxe":      {"name": "XML External Entities",      "cwe": "CWE-611",  "accent": "#8fd14f"},
    "authz":    {"name": "Access Control / IDOR",      "cwe": "CWE-639",  "accent": "#ffd60a"},
    "authn":    {"name": "Authentication / Session",   "cwe": "CWE-287",  "accent": "#ffe066"},
    "jwt":      {"name": "Token / JWT Handling",       "cwe": "CWE-347",  "accent": "#e8c547"},
    "crypto":   {"name": "Weak Crypto / Randomness",   "cwe": "CWE-327",  "accent": "#9fb4c7"},
    "tls":      {"name": "TLS Verification Disabled",  "cwe": "CWE-295",  "accent": "#7aa2c7"},
    "secret":   {"name": "Hardcoded Secret",           "cwe": "CWE-798",  "accent": "#ff3b30"},
    "redirect": {"name": "Open Redirect",              "cwe": "CWE-601",  "accent": "#a0c4ff"},
    "cors":     {"name": "CORS / Origin Policy",       "cwe": "CWE-942",  "accent": "#8ecae6"},
    "csrf":     {"name": "CSRF Protection Disabled",   "cwe": "CWE-352",  "accent": "#c3a6ff"},
    "proto":    {"name": "Mass Assignment / Prototype", "cwe": "CWE-1321", "accent": "#f7a1c4"},
    "memory":   {"name": "Memory Safety",              "cwe": "CWE-787",  "accent": "#ff6b6b"},
    "race":     {"name": "Race Condition / TOCTOU",    "cwe": "CWE-367",  "accent": "#a8dadc"},
    "dos":      {"name": "DoS / Resource Exhaustion",  "cwe": "CWE-400",  "accent": "#adb5bd"},
    "config":   {"name": "Dangerous Configuration",    "cwe": "CWE-489",  "accent": "#ced4da"},
    "supply":   {"name": "Supply Chain / CI",          "cwe": "CWE-1357", "accent": "#e07a5f"},
    "suppress": {"name": "Suppressed Warning / TODO",  "cwe": "CWE-1078", "accent": "#bfa66b"},
}

PY = ("python",)
JS = ("javascript", "typescript", "vue", "svelte", "astro", "ejs", "handlebars")
PHP = ("php", "blade")
JAVA = ("java", "kotlin", "scala", "groovy", "gradle")
GO = ("go",)
RB = ("ruby",)
CFAM = ("c", "cpp", "objc")
CS = ("csharp", "vbnet")
SH = ("shell", "powershell", "batch")
CFG = ("yaml", "json", "toml", "ini", "dotenv", "terraform", "hcl", "dockerfile", "xml",
       "properties", "nginx", "apache", "config", "gradle")
WEBTMPL = ("html", "jinja", "twig", "blade", "ejs", "handlebars", "pug", "erb", "vue", "svelte")

# (id, category, title, weight, langs, pattern, case_insensitive, why)
RULES: list[tuple] = [
    # ---- python
    ("py.shell_true", "cmd", "subprocess with shell=True", 9, PY,
     r"subprocess\.(?:run|call|check_output|check_call|Popen)\s*\((?:[^)]|\n)*?shell\s*=\s*True", False,
     "Arguments are handed to a shell; any attacker-controlled substring becomes a command."),
    ("py.os_system", "cmd", "os.system / os.popen", 8, PY,
     r"\bos\.(?:system|popen|popen2|popen3|popen4)\s*\(", False,
     "Full shell execution, no argument separation."),
    ("py.os_exec", "cmd", "os.exec* / os.spawn*", 7, PY,
     r"\bos\.(?:execl|execle|execlp|execv|execve|execvp|execvpe|spawnl|spawnv|spawnve)\s*\(", False,
     "Process replacement with caller-supplied program or argv."),
    ("py.subprocess_var", "cmd", "subprocess with built argv", 5, PY,
     r"subprocess\.(?:run|Popen|call|check_output)\s*\(\s*(?:f[\"']|\[[^\]]*(?:\+|f[\"'])|[a-z_][\w.]*\s*[,)])", False,
     "Command or argv is assembled at runtime, worth tracing to its source."),
    ("py.eval", "code", "eval()", 8, PY, r"(?<![\w.])eval\s*\(", False,
     "Arbitrary Python expression execution if the string is influenced by input."),
    ("py.exec", "code", "exec()", 8, PY, r"(?<![\w.])exec\s*\(", False,
     "Arbitrary Python statement execution."),
    ("py.compile", "code", "compile() to exec/eval", 6, PY,
     r"\bcompile\s*\((?:[^)]|\n)*?[\"'](?:exec|eval|single)[\"']", False,
     "Dynamic code path; check who controls the source string."),
    ("py.import_dyn", "code", "dynamic import by name", 5, PY,
     r"(?:__import__|importlib\.import_module)\s*\(\s*(?!['\"])", False,
     "Module name is computed; can lead to arbitrary module load."),
    ("py.pickle", "deser", "pickle / dill load", 9, PY,
     r"\b(?:pickle|cPickle|dill|cloudpickle|joblib)\.loads?\s*\(", False,
     "Pickle deserialisation is RCE by design for untrusted data."),
    ("py.yaml_load", "deser", "yaml.load without SafeLoader", 8, PY,
     r"yaml\.(?:unsafe_load|full_load|load)\s*\((?![^)]*(?:SafeLoader|BaseLoader|safe))", False,
     "Non-safe YAML loaders can construct arbitrary Python objects."),
    ("py.marshal", "deser", "marshal / shelve / jsonpickle", 7, PY,
     r"\b(?:marshal\.loads?|shelve\.open|jsonpickle\.decode)\s*\(", False,
     "Object graph reconstruction from a byte stream."),
    ("py.np_pickle", "deser", "numpy/pandas pickle load", 7, PY,
     r"(?:read_pickle\s*\(|np(?:umpy)?\.load\s*\((?:[^)]|\n)*?allow_pickle\s*=\s*True|torch\.load\s*\()", False,
     "These loaders unpickle; a crafted model or dataframe is code execution."),
    ("py.sql_fmt", "sqli", "SQL built by f-string/format/%", 8, PY,
     r"(?:execute|executemany|executescript|raw|cursor\.execute)\s*\(\s*(?:f[\"']|[\"'][^\"']*[\"']\s*(?:%|\+|\.format))", False,
     "Query text is concatenated instead of parameterised."),
    ("py.sql_concat", "sqli", "query string concatenation", 7, PY,
     r"(?:SELECT|INSERT\s+INTO|UPDATE|DELETE\s+FROM)\b[^\"'\n]{0,120}[\"']\s*(?:\+|%|\.format\(|\})", True,
     "Raw SQL assembled from variables."),
    ("py.django_raw", "sqli", "Django .raw()/.extra()", 6, PY, r"\.(?:raw|extra)\s*\(", False,
     "ORM escape hatches that accept raw SQL fragments."),
    ("py.sqlalchemy_text", "sqli", "SQLAlchemy text() with interpolation", 7, PY,
     r"text\s*\(\s*(?:f[\"']|[\"'][^\"']*[\"']\s*(?:%|\+|\.format))", False,
     "text() does not parameterise interpolated values."),
    ("py.path_join_input", "path", "path built from request data", 8, PY,
     r"(?:os\.path\.join|Path\s*\(|open\s*\()(?:[^)\n]{0,80})(?:request\.|params\[|args\[|query|filename|user_|kwargs\[)", False,
     "Traversal candidate: attacker-controlled component in a filesystem path."),
    ("py.open_var", "path", "open() with computed path", 5, PY,
     r"\bopen\s*\(\s*(?:f[\"']|[a-z_][\w.]*\s*(?:\+|,|\)))", False,
     "File path is dynamic; check normalisation and base-dir containment."),
    ("py.send_file", "path", "send_file / send_from_directory", 6, PY,
     r"\b(?:send_file|send_from_directory|FileResponse|X-Sendfile|serve)\s*\(", False,
     "Direct file serving; classic arbitrary-read surface."),
    ("py.extractall", "path", "archive extractall (zip slip)", 7, PY,
     r"\.extractall\s*\(", False,
     "Archive members with ../ or absolute paths escape the target directory."),
    ("py.requests_var", "ssrf", "outbound HTTP to computed URL", 6, PY,
     r"requests\.(?:get|post|put|patch|delete|head|request)\s*\(\s*(?:f[\"']|url|[a-z_][\w.]*\s*[,)])", False,
     "Server-side fetch where the URL is not a literal."),
    ("py.urlopen", "ssrf", "urlopen / httpx / aiohttp fetch", 6, PY,
     r"(?:urllib\.request\.urlopen|urlopen|httpx\.(?:get|post|Client)|aiohttp\.ClientSession\(\)\.(?:get|post))\s*\(", False,
     "Outbound request primitive; check host allow-listing."),
    ("py.tls_off", "tls", "certificate verification disabled", 8, PY,
     r"(?:requests|httpx|session|client|urllib3|aiohttp)\b[^\n]{0,80}verify\s*=\s*False|verify\s*=\s*False\s*,?\s*(?:#[^\n]*)?$|ssl\._create_unverified_context|CERT_NONE|check_hostname\s*=\s*False", False,
     "TLS trust is switched off, enabling MitM."),
    ("py.mark_safe", "xss", "mark_safe / format_html on variable", 6, PY,
     r"\b(?:mark_safe|SafeString|SafeText)\s*\(", False,
     "Marks a possibly tainted string as trusted HTML."),
    ("py.autoescape_off", "xss", "autoescaping disabled", 7, PY + WEBTMPL,
     r"autoescape\s*=\s*False|\{%\s*autoescape\s+off|\|\s*safe\b|\{\{\s*[^}]+\|\s*safe", False,
     "Template output is not HTML-escaped."),
    ("py.render_string", "tmpl", "render_template_string / Template()", 8, PY,
     r"(?:render_template_string\s*\(|Template\s*\(\s*(?:f[\"']|[a-z_]\w*)|from_string\s*\()", False,
     "Server-side template injection leads to RCE in Jinja."),
    ("py.xml", "xxe", "XML parser without hardening", 5, PY,
     r"(?:xml\.etree\.ElementTree|xml\.dom\.minidom|xml\.sax|lxml\.etree|xmlrpc\.(?:client|server))", False,
     "Default parsers may resolve entities or be DoS-prone."),
    ("py.weak_hash", "crypto", "MD5 / SHA1", 5, PY,
     r"hashlib\.(?:md5|sha1)\s*\(|Crypto\.Hash\.(?:MD5|SHA1)", False,
     "Broken hash; a problem for signatures, passwords or dedup security."),
    ("py.weak_random", "crypto", "random module for security value", 4, PY,
     r"\brandom\.(?:random|randint|choice|randrange|sample|shuffle|getrandbits)\s*\(", False,
     "Predictable PRNG; only matters if the value is a token/secret."),
    ("py.cipher_weak", "crypto", "ECB mode / static IV / DES", 7, PY,
     r"MODE_ECB|DES\.new|ARC4|Blowfish\.new|AES\.new\s*\((?:[^)]|\n)*?iv\s*=\s*[b]?[\"']", False,
     "Mode or key material choice leaks plaintext structure or is forgeable."),
    ("py.jwt_noverify", "jwt", "JWT signature not verified", 9, PY,
     r"jwt\.decode\s*\((?:[^)]|\n)*?(?:verify\s*=\s*False|verify_signature[\"']?\s*:\s*False|algorithms\s*=\s*\[\s*[\"']none)", True,
     "Unverified tokens mean full authentication bypass."),
    ("py.jwt_decode", "jwt", "JWT decode path", 5, PY,
     r"jwt\.(?:decode|get_unverified_header|decode_complete)\s*\(", False,
     "Token parsing; check algorithm pinning and audience checks."),
    ("py.redirect_var", "redirect", "redirect to computed target", 5, PY,
     r"redirect\s*\(\s*(?:request\.|[a-z_][\w.]*\s*[,)]|f[\"'])", False,
     "Open redirect if the destination is not validated."),
    ("py.cors_wild", "cors", "wildcard CORS", 6, PY + CFG,
     r"(?:Access-Control-Allow-Origin[\"']?\s*[:,=]\s*[\"']\*|CORS\s*\((?:[^)]|\n)*?origins\s*=\s*[\"'\[]?\*|supports_credentials\s*=\s*True)", False,
     "Any origin can read responses; lethal together with credentials."),
    ("py.csrf_off", "csrf", "CSRF protection disabled", 7, PY,
     r"csrf_exempt|csrf\.exempt|WTF_CSRF_ENABLED\s*=\s*False|CSRF_ENABLED\s*=\s*False", False,
     "State-changing endpoint reachable cross-site."),
    ("py.idor", "authz", "object lookup keyed on request id", 7, PY,
     r"objects\.(?:get|filter|get_or_404|get_object_or_404)\s*\(\s*(?:pk|id|uuid|user_id)\s*=\s*(?:request|self\.request|kwargs|params|data)", False,
     "Direct object reference without an ownership check is the classic IDOR."),
    ("py.authz_marker", "authz", "permission / role check", 4, PY,
     r"(?:@login_required|@permission_required|@user_passes_test|has_perm|is_staff|is_superuser|IsAuthenticated|permission_classes)", False,
     "Authorisation logic: read it for gaps and for endpoints that omit it."),
    ("py.debug_on", "config", "debug mode enabled", 5, PY,
     r"DEBUG\s*=\s*True|app\.run\s*\((?:[^)]|\n)*?debug\s*=\s*True", False,
     "Debug consoles and tracebacks leak internals; Werkzeug console is RCE."),
    ("py.mktemp", "race", "insecure temp file", 5, PY,
     r"tempfile\.mktemp\s*\(|/tmp/[\w.\-]+[\"']", False,
     "Predictable temp path invites symlink/TOCTOU attacks."),
    ("py.upload", "upload", "file upload handling", 6, PY,
     r"request\.files|FileField|ImageField|UploadFile|MultiPartParser|save\s*\(\s*os\.path\.join", False,
     "Upload path: check extension, content type, storage location and execution."),

    # ---- javascript / typescript
    ("js.eval", "code", "eval()", 8, JS, r"(?<![\w.$])eval\s*\(", False,
     "Arbitrary JS execution."),
    ("js.new_function", "code", "new Function()", 7, JS, r"new\s+Function\s*\(", False,
     "Compiles a string into code."),
    ("js.vm", "code", "vm / vm2 sandbox execution", 8, JS,
     r"\bvm\d?\.(?:runInNewContext|runInThisContext|runInContext|createScript|Script)\s*\(|require\s*\(\s*['\"]vm2", False,
     "Node sandboxes are routinely escaped; treat as arbitrary execution."),
    ("js.settimeout_str", "code", "setTimeout/Interval with string", 5, JS,
     r"set(?:Timeout|Interval)\s*\(\s*[\"'`]", False,
     "String argument is evaluated as code."),
    # `exec(` bare is the destructured child_process import; `x.exec(` is RegExp.prototype.exec,
    # which is far more common in JS and must not read as command execution.
    ("js.child_exec", "cmd", "child_process exec", 8, JS,
     r"(?<![\w$.])exec(?:Sync)?\s*\(|\b(?:child_process|childProcess|cp)\s*\.\s*exec(?:Sync|File|FileSync)?\s*\(|require\s*\(\s*['\"]child_process", False,
     "exec spawns a shell; template literals make injection trivial."),
    ("js.spawn_shell", "cmd", "spawn with shell:true", 8, JS,
     r"(?:spawn|execFile)(?:Sync)?\s*\((?:[^)]|\n)*?shell\s*:\s*true", False,
     "Shell interpretation restored, argument escaping lost."),
    ("js.innerhtml", "xss", "innerHTML / outerHTML assignment", 6, JS + WEBTMPL,
     r"\.(?:innerHTML|outerHTML)\s*(?:\+)?=", False,
     "DOM XSS sink."),
    ("js.dangerous_html", "xss", "dangerouslySetInnerHTML", 7, JS,
     r"dangerouslySetInnerHTML", False,
     "React bypass of escaping; check the value's origin."),
    ("js.doc_write", "xss", "document.write", 6, JS, r"document\.write(?:ln)?\s*\(", False,
     "Writes unescaped markup into the page."),
    ("js.vhtml", "xss", "v-html / ng-bind-html", 6, JS + WEBTMPL,
     r"v-html\s*=|ng-bind-html|\[innerHTML\]\s*=", False,
     "Framework raw-HTML binding."),
    ("js.jquery_sink", "xss", "jQuery html()/append() sink", 4, JS,
     r"\$\([^)]{0,60}\)\s*\.\s*(?:html|append|prepend|after|before|replaceWith)\s*\(", False,
     "jQuery HTML sinks parse and execute scripts."),
    ("js.sql_template", "sqli", "SQL via template literal or +", 8, JS,
     r"(?:query|execute|raw|queryRaw|executeRaw)\s*\(\s*(?:`[^`]*\$\{|[\"'][^\"']*[\"']\s*\+)", False,
     "Interpolated SQL instead of bound parameters."),
    ("js.orm_unsafe", "sqli", "ORM raw escape hatch", 7, JS,
     r"(?:sequelize\.literal|Sequelize\.literal|\$queryRawUnsafe|\$executeRawUnsafe|knex\.raw|db\.raw)\s*\(", False,
     "Raw SQL through the ORM, usually unparameterised."),
    ("js.mongo_where", "nosql", "Mongo $where / $function", 7, JS,
     r"\$where|\$function|mapReduce\s*\(|\$accumulator", False,
     "Server-side JS evaluation inside the database."),
    # a Sequelize `{ where: ... }` is parameterised, so it is an access-control question,
    # not operator injection; those go to js.orm_idor below.
    ("js.mongo_req", "nosql", "query object from req.*", 6, JS,
     r"\.(?:find|findOne|findOneAndUpdate|updateOne|updateMany|deleteOne|deleteMany|count|aggregate)\s*\(\s*(?:req\.(?:body|query|params)\b|\{(?!\s*where\b)\s*[^}]{0,80}req\.)", False,
     "Operator injection ($ne, $gt, $regex) when a raw object is trusted."),
    ("js.orm_idor", "authz", "ORM lookup keyed on a request value", 6, JS,
     r"\.(?:findOne|findByPk|findAll|findOrCreate|update|destroy|count)\s*\(\s*\{[^}]{0,120}\bwhere\b[^}]{0,120}req\.(?:params|body|query)", False,
     "Direct object reference: check the row is scoped to the caller, not just to the id."),
    ("js.path_req", "path", "path built from req.*", 8, JS,
     r"(?:path\.(?:join|resolve|normalize))\s*\((?:[^)]|\n){0,90}req\.(?:params|query|body|headers)", False,
     "Traversal candidate with request-controlled segment."),
    ("js.fs_var", "path", "fs operation on computed path", 5, JS,
     r"fs(?:\.promises)?\.(?:readFile|readFileSync|createReadStream|writeFile|writeFileSync|unlink|rename|rmdir|readdir)\s*\(\s*(?:[a-z_$][\w.$]*|`)", False,
     "Filesystem access with a non-literal path."),
    ("js.sendfile", "path", "res.sendFile / download", 6, JS,
     r"res\.(?:sendFile|download|attachment)\s*\(", False,
     "Serves a file chosen at runtime."),
    ("js.zip_extract", "path", "archive extraction", 6, JS,
     r"(?:extract|unzip|tar\.x)\s*\(|decompress\s*\(|adm-zip", False,
     "Zip-slip if member paths are not normalised."),
    # bare `request(` is supertest in every Node test suite, so it needs a URL-ish argument
    ("js.fetch_var", "ssrf", "outbound fetch to computed URL", 6, JS,
     r"(?:axios|fetch|superagent|needle|undici|got)\s*(?:\.\s*(?:get|post|put|patch|delete|head))?\s*\(\s*(?:`[^`]*\$\{|[a-z_$][\w.$]*\s*[,)]|req\.)|\brequest\s*\(\s*(?:`[^`]*\$\{|['\"]https?://|(?:url|uri|target|endpoint|link)\b)", False,
     "Server-side request with a dynamic URL."),
    ("js.tls_off", "tls", "TLS verification disabled", 8, JS,
     r"rejectUnauthorized\s*:\s*false|NODE_TLS_REJECT_UNAUTHORIZED\s*[=:]\s*['\"]?0|strictSSL\s*:\s*false", False,
     "Node will accept any certificate."),
    ("js.cors_wild", "cors", "permissive CORS", 6, JS,
     r"(?:Access-Control-Allow-Origin[\"']?\s*[,:]\s*[\"']\*|cors\s*\(\s*\{(?:[^}]|\n)*?origin\s*:\s*(?:true|['\"]\*)|credentials\s*:\s*true)", False,
     "Wildcard or reflected origin, especially with credentials."),
    ("js.jwt_weak", "jwt", "JWT decoded without verify", 8, JS,
     r"jwt\.decode\s*\(|algorithms\s*:\s*\[\s*['\"]none|ignoreExpiration\s*:\s*true|verify\s*:\s*false", False,
     "decode() does not check the signature; none-alg is a bypass."),
    ("js.deser", "deser", "unsafe object deserialisation", 8, JS,
     r"node-serialize|serialize-javascript|funcster|\bunserialize\s*\(|eval\s*\(\s*JSON", False,
     "These libraries reconstruct functions from data."),
    ("js.yaml_load", "deser", "yaml.load (non-safe)", 6, JS,
     r"yaml\.load\s*\((?![^)]*(?:safe|JSON_SCHEMA|CORE_SCHEMA))", False,
     "Legacy js-yaml load can instantiate custom types."),
    # a bare `.set(` is any setter (Angular signals, Maps); require the lodash/merge idiom
    ("js.proto_pollute", "proto", "deep merge / dynamic key write", 6, JS,
     r"(?:\b_|lodash)\s*\.\s*(?:merge|mergeWith|defaultsDeep|setWith|zipObjectDeep|set)\s*\(|\b(?:merge|mergeWith|defaultsDeep|deepExtend|deepmerge|extend)\s*\(\s*(?:\{\}|target|dest|options|config|defaults)\b|Object\.assign\s*\(\s*(?:\{\}|\w+)\s*,\s*req\.", False,
     "__proto__ / constructor keys can poison prototypes."),
    ("js.mass_assign", "proto", "model created straight from req.body", 6, JS,
     r"(?:\.create|\.update|\.save|new\s+\w+)\s*\(\s*req\.body", False,
     "Mass assignment lets a client set fields like isAdmin."),
    ("js.regex_dyn", "dos", "RegExp built from variable", 5, JS,
     r"new\s+RegExp\s*\(\s*(?:[a-z_$][\w.$]*|req\.|`)", False,
     "ReDoS or filter bypass through crafted pattern input."),
    ("js.weak_hash", "crypto", "MD5 / SHA1 digest", 5, JS,
     r"createHash\s*\(\s*['\"](?:md5|sha1)['\"]", False,
     "Broken hash primitive."),
    ("js.math_random", "crypto", "Math.random() for value", 4, JS,
     r"Math\.random\s*\(\s*\)", False,
     "Not cryptographically random; critical if used for tokens or IDs."),
    ("js.cookie_weak", "authn", "insecure cookie flags", 6, JS,
     r"(?:httpOnly|secure)\s*:\s*false|sameSite\s*:\s*['\"](?:none|None)['\"]", False,
     "Session cookie reachable by script or sent cross-site."),
    ("js.token_storage", "authn", "token in localStorage", 5, JS,
     r"(?:localStorage|sessionStorage)\.setItem\s*\(\s*['\"][^'\"]*(?:token|jwt|auth|session|secret|key)", True,
     "XSS-readable credential storage."),
    ("js.upload", "upload", "upload middleware", 5, JS,
     r"multer\s*\(|formidable|busboy|express-fileupload|graphql-upload", False,
     "Upload handling: validate type, size, name and storage path."),
    # a bare `location =` is usually a variable named location (Angular injects one)
    ("js.redirect_var", "redirect", "redirect to computed target", 6, JS,
     r"res\.redirect\s*\(\s*(?!['\"]/)|(?:window|document|top|self|parent)\s*\.\s*location(?:\s*\.\s*href)?\s*=\s*(?![\"']\s*/)|\blocation\s*\.\s*(?:href|replace|assign)\s*(?:=\s*(?![\"']\s*/)|\(\s*(?!['\"]/))", False,
     "Open redirect / DOM-based navigation sink."),
    ("js.graphql_open", "config", "GraphQL introspection/playground on", 4, JS,
     r"introspection\s*:\s*true|playground\s*:\s*true|graphiql\s*:\s*true", False,
     "Schema exposure in production eases mapping of hidden mutations."),
    ("js.ssti", "tmpl", "template compiled at runtime", 8, JS,
     r"\b(?:pug|jade|ejs|handlebars|hbs|nunjucks|eta|liquid|twig|mustache|dot|swig)\s*\.\s*(?:compile|compileFile|render|renderString|renderFile)\s*\(|res\.render\s*\(\s*(?!['\"])", False,
     "Server-side template injection: a template built from input is remote code execution."),
    ("js.ng_bypass", "xss", "Angular DomSanitizer bypass", 7, JS,
     r"bypassSecurityTrust(?:Html|Script|Style|Url|ResourceUrl)\s*\(", False,
     "Explicitly marks a value as trusted markup, defeating Angular's escaping."),
    ("js.res_reflect", "xss", "request data written to the response", 6, JS,
     r"res\.(?:send|write|end)\s*\([^)\n]{0,80}req\.(?:query|body|params|headers)", False,
     "Reflected XSS candidate: input echoed into an HTML response."),
    ("js.header_inject", "redirect", "response header from request data", 6, JS,
     r"res\.(?:setHeader|writeHead|append|header|location)\s*\([^)\n]{0,80}req\.", False,
     "Header injection / open redirect if the value is not validated."),
    ("js.dyn_require", "code", "module loaded by computed name", 6, JS,
     r"\brequire\s*\(\s*(?!['\"])[a-z_$`]|\bimport\s*\(\s*(?!['\"])[a-z_$`]", False,
     "A require path under attacker control can load arbitrary code."),

    # ---- php
    ("php.shell", "cmd", "shell execution function", 9, PHP,
     r"\b(?:system|exec|shell_exec|passthru|popen|proc_open|pcntl_exec)\s*\(", False,
     "Direct command execution."),
    ("php.eval", "code", "eval / assert / create_function", 9, PHP,
     r"\b(?:eval|assert|create_function)\s*\(|preg_replace\s*\(\s*[\"'][^\"']*/\w*e", False,
     "Arbitrary PHP execution."),
    ("php.include_var", "path", "dynamic include/require", 8, PHP,
     r"(?:include|include_once|require|require_once)\s*\(?\s*[\"']?\s*\$", False,
     "Local/remote file inclusion leading to code execution."),
    ("php.unserialize", "deser", "unserialize()", 9, PHP, r"\bunserialize\s*\(", False,
     "Object injection via magic methods."),
    ("php.sql", "sqli", "query with interpolated variable", 8, PHP,
     r"(?:mysql_query|mysqli_query|->query|->exec|->prepare)\s*\(\s*[\"'][^\"']*(?:\$|\{\$)", False,
     "Variable interpolated directly into SQL."),
    ("php.echo_input", "xss", "superglobal echoed", 8, PHP,
     r"(?:echo|print|printf)\s+[^;\n]{0,40}\$_(?:GET|POST|REQUEST|COOKIE)", False,
     "Reflected XSS straight from the request."),
    ("php.file_var", "path", "file function on variable", 7, PHP,
     r"\b(?:file_get_contents|file_put_contents|fopen|readfile|unlink|copy|rename|scandir|glob)\s*\(\s*\$", False,
     "Arbitrary file read/write/delete candidate."),
    ("php.upload", "upload", "$_FILES / move_uploaded_file", 7, PHP,
     r"\$_FILES|move_uploaded_file\s*\(", False,
     "Upload handling; webshell risk if the target dir is served."),
    ("php.extract", "proto", "extract() on request data", 8, PHP,
     r"\bextract\s*\(\s*\$(?:_|GLOBALS)", False,
     "Overwrites arbitrary local variables from input."),
    ("php.curl_var", "ssrf", "cURL to variable URL", 7, PHP,
     r"CURLOPT_URL\s*,\s*\$|curl_init\s*\(\s*\$", False,
     "Server-side fetch with user-controlled target."),
    ("php.tls_off", "tls", "cURL verification off", 8, PHP,
     r"CURLOPT_SSL_VERIFY(?:PEER|HOST)\s*,\s*(?:false|0|FALSE)", False,
     "TLS trust disabled."),
    ("php.header_redirect", "redirect", "Location header from variable", 6, PHP,
     r"header\s*\(\s*[\"']Location:[^\"']*[\"']?\s*\.\s*\$|header\s*\(\s*\$", False,
     "Open redirect / header injection."),
    ("php.weak_hash", "crypto", "md5 / sha1 password handling", 5, PHP,
     r"\b(?:md5|sha1|crc32)\s*\(", False,
     "Unsuitable for passwords or integrity."),
    ("php.xxe", "xxe", "entity loading enabled", 7, PHP,
     r"libxml_disable_entity_loader\s*\(\s*(?:false|FALSE|0)|LIBXML_NOENT|simplexml_load_(?:string|file)\s*\(", False,
     "XXE file read / SSRF."),

    # ---- java / kotlin
    ("java.exec", "cmd", "Runtime.exec / ProcessBuilder", 8, JAVA,
     r"Runtime\.getRuntime\s*\(\s*\)\s*\.exec\s*\(|new\s+ProcessBuilder\s*\(", False,
     "Command execution; string form goes through a shell-ish split."),
    ("java.deser", "deser", "Java object deserialisation", 9, JAVA,
     r"new\s+ObjectInputStream|\.readObject\s*\(\s*\)|XStream|new\s+Yaml\s*\(\s*\)|Kryo|SerializationUtils\.deserialize", False,
     "Gadget-chain RCE surface."),
    ("java.jackson_poly", "deser", "Jackson polymorphic typing", 8, JAVA,
     r"enableDefaultTyping|@JsonTypeInfo\s*\(\s*use\s*=\s*Id\.CLASS|activateDefaultTyping", False,
     "Type-driven instantiation of arbitrary classes."),
    ("java.sql_concat", "sqli", "JDBC/JPQL string concatenation", 8, JAVA,
     r"(?:executeQuery|executeUpdate|createQuery|createNativeQuery|execute)\s*\(\s*(?:[\"'][^\"']*[\"']\s*\+|\w+\s*\+\s*[\"'])", False,
     "Unparameterised query assembly."),
    ("java.expr", "code", "expression engine evaluation", 9, JAVA,
     r"ScriptEngineManager|GroovyShell|SpelExpressionParser|MVEL\.|OgnlContext|Ognl\.|JexlEngine|new\s+ELProcessor", False,
     "Expression languages evaluate attacker strings as code."),
    ("java.path", "path", "File/Path from request value", 6, JAVA,
     r"new\s+File\s*\(\s*(?:\w+\s*\+|request\.get)|Paths\.get\s*\(\s*(?:\w+\s*\+|request\.get)", False,
     "Traversal candidate."),
    ("java.xxe", "xxe", "XML factory without hardening", 7, JAVA,
     r"DocumentBuilderFactory|SAXParserFactory|XMLInputFactory|TransformerFactory|new\s+SAXReader|Unmarshaller", False,
     "Needs explicit FEATURE_SECURE_PROCESSING / disallow-doctype."),
    ("java.ssrf", "ssrf", "URL / HTTP client from variable", 5, JAVA,
     r"new\s+URL\s*\(\s*\w+|RestTemplate|WebClient\.create\s*\(\s*\w+|HttpRequest\.newBuilder\s*\(\s*\w+", False,
     "Outbound request target is dynamic."),
    ("java.tls_off", "tls", "trust-all TrustManager", 8, JAVA,
     r"X509TrustManager|TrustAllCerts|ALLOW_ALL_HOSTNAME_VERIFIER|setHostnameVerifier|checkServerTrusted\s*\([^)]*\)\s*(?:throws[^\{]*)?\{\s*\}", False,
     "Certificate validation bypassed."),
    ("java.crypto", "crypto", "weak cipher / hash / Random", 6, JAVA,
     r"MessageDigest\.getInstance\s*\(\s*\"(?:MD5|SHA-?1)|Cipher\.getInstance\s*\(\s*\"(?:DES|RC2|RC4|AES/ECB|.*NoPadding)|new\s+Random\s*\(", False,
     "Weak primitive or predictable randomness."),
    ("java.csrf_off", "csrf", "Spring CSRF disabled", 8, JAVA,
     r"\.csrf\s*\(\s*\)\s*\.disable|csrf\(\)\.disable|CsrfProtectionMatcher", False,
     "State-changing endpoints exposed cross-site."),
    ("java.authz", "authz", "authorisation annotation / matcher", 5, JAVA,
     r"@PreAuthorize|@PostAuthorize|@Secured|@RolesAllowed|hasRole\s*\(|hasAuthority\s*\(|antMatchers\s*\(|requestMatchers\s*\(", False,
     "Access-control config; look for permitAll and overly broad patterns."),
    ("java.permit_all", "authz", "permitAll / anonymous access", 6, JAVA,
     r"permitAll\s*\(\s*\)|\.anonymous\s*\(\s*\)|@AllowAnonymous", False,
     "Explicitly unauthenticated route."),

    # ---- go
    ("go.exec", "cmd", "exec.Command", 7, GO, r"exec\.Command(?:Context)?\s*\(", False,
     "Process execution; sh -c form is injectable."),
    ("go.sql_fmt", "sqli", "query built with Sprintf/concat", 8, GO,
     r"(?:Query|QueryRow|Exec|Raw|Select)\s*\(\s*(?:fmt\.Sprintf|[\"'][^\"']*[\"']\s*\+)", False,
     "Unparameterised query."),
    ("go.path", "path", "file op with request value", 7, GO,
     r"(?:os\.(?:Open|OpenFile|ReadFile|Create|Remove|RemoveAll)|ioutil\.ReadFile|filepath\.Join|http\.ServeFile)\s*\((?:[^)]|\n){0,80}(?:r\.URL|mux\.Vars|c\.Param|vars\[|r\.FormValue)", False,
     "Traversal candidate in a handler."),
    ("go.ssrf", "ssrf", "HTTP request to computed URL", 6, GO,
     r"http\.(?:Get|Post|Head|PostForm|NewRequest(?:WithContext)?)\s*\((?:[^)]|\n){0,60}(?:fmt\.Sprintf|[a-z]\w*Url|url\b|r\.FormValue)", False,
     "Dynamic outbound target."),
    ("go.tls_off", "tls", "InsecureSkipVerify", 8, GO, r"InsecureSkipVerify\s*:\s*true", False,
     "TLS certificate check disabled."),
    ("go.template_raw", "xss", "template.HTML / text/template for HTML", 6, GO,
     r"template\.(?:HTML|JS|URL|HTMLAttr)\s*\(|\"text/template\"", False,
     "Bypasses contextual escaping."),
    ("go.crypto", "crypto", "math/rand or weak hash", 5, GO,
     r"\"math/rand\"|md5\.(?:New|Sum)|sha1\.(?:New|Sum)|des\.NewCipher|rc4\.NewCipher", False,
     "Predictable randomness or broken hash."),
    ("go.deser", "deser", "gob / yaml decode", 5, GO,
     r"gob\.NewDecoder|yaml\.Unmarshal|xml\.Unmarshal", False,
     "Structured decode of untrusted bytes."),
    ("go.cors", "cors", "permissive CORS", 6, GO,
     r"AllowAllOrigins\s*:\s*true|Access-Control-Allow-Origin\"\s*,\s*\"\*|AllowOrigins\s*:\s*\[\]string\{\s*\"\*\"", False,
     "Any origin allowed."),

    # ---- ruby
    ("rb.exec", "cmd", "shell execution", 8, RB,
     r"\b(?:system|exec|spawn)\s*[\(\"']|IO\.popen|Open3\.(?:capture|popen|pipeline)|%x[\(\{\[]|`[^`\n]*#\{", False,
     "Command execution, interpolation is direct injection."),
    ("rb.eval", "code", "eval / send / const_get", 7, RB,
     r"\b(?:eval|instance_eval|class_eval|module_eval|binding\.eval)\s*[\(\s]|\b(?:send|public_send|const_get|define_method)\s*\(\s*(?:params|\w+)", False,
     "Dynamic dispatch/eval reachable from parameters."),
    ("rb.deser", "deser", "Marshal / YAML load", 8, RB,
     r"Marshal\.load|YAML\.load\s*\((?![^)]*safe)|Oj\.load|Psych\.load\s*\(", False,
     "Object instantiation from untrusted data."),
    ("rb.sql", "sqli", "interpolated SQL/where", 8, RB,
     r"(?:where|find_by_sql|execute|select_all|order|group|pluck)\s*\(?\s*[\"'][^\"']*#\{", False,
     "String interpolation inside a query fragment."),
    ("rb.permit_all", "proto", "params.permit!", 7, RB, r"params\.permit!|params\.require\s*\([^)]*\)\.permit!", False,
     "Mass assignment of every submitted attribute."),
    ("rb.render_inline", "tmpl", "render inline/text/html", 6, RB,
     r"render\s+(?:inline|text|html|body)\s*:", False,
     "ERB template injection or raw HTML output."),
    ("rb.html_safe", "xss", "html_safe / raw", 6, RB + WEBTMPL,
     r"\.html_safe|\braw\s+\w|<%==", False,
     "Escaping disabled for this output."),
    ("rb.kernel_open", "ssrf", "Kernel#open / URI.open", 7, RB,
     r"(?<!File\.)\bopen\s*\(\s*(?:params|\w+)|URI\.(?:open|parse)\s*\(\s*params", False,
     "Kernel#open with a pipe prefix executes commands, and fetches URLs."),
    ("rb.csrf_off", "csrf", "forgery protection skipped", 7, RB,
     r"skip_before_action\s+:verify_authenticity_token|protect_from_forgery\s+with:\s*:null_session", False,
     "CSRF check removed."),
    ("rb.send_file", "path", "send_file / send_data", 5, RB, r"send_file|send_data", False,
     "Dynamic file response."),

    # ---- c / c++
    ("c.unsafe_str", "memory", "strcpy / sprintf / gets", 8, CFAM,
     r"\b(?:strcpy|strcat|sprintf|vsprintf|gets|getwd|scanf|sscanf|strtok)\s*\(", False,
     "No bounds checking; classic stack overflow."),
    ("c.mem_ops", "memory", "memcpy / alloca / realloc", 5, CFAM,
     r"\b(?:memcpy|memmove|alloca|realloc|strncpy|snprintf)\s*\(", False,
     "Length arithmetic worth auditing for overflow."),
    ("c.format", "memory", "non-literal format string", 7, CFAM,
     r"\b(?:printf|fprintf|sprintf|syslog)\s*\(\s*(?:[a-z_]\w*\s*[,)])", False,
     "Format-string vulnerability."),
    ("c.system", "cmd", "system / popen / exec*", 8, CFAM,
     r"\b(?:system|popen|execl|execlp|execvp|execve)\s*\(", False,
     "Command execution."),
    ("c.alloc_math", "memory", "allocation size arithmetic", 5, CFAM,
     r"(?:malloc|calloc|new\s*\[)\s*\(?\s*\w+\s*[*+]\s*\w+", False,
     "Integer overflow in a size computation."),
    ("c.tmp", "race", "mktemp / tmpnam", 5, CFAM, r"\b(?:mktemp|tmpnam|tempnam)\s*\(", False,
     "Predictable temp name, TOCTOU."),

    # ---- c#
    ("cs.sql", "sqli", "SqlCommand with concatenation", 8, CS,
     r"new\s+Sql(?:Command|DataAdapter)\s*\(\s*(?:\$?\"[^\"]*(?:\{|\"\s*\+)|\w+\s*\+)|CommandText\s*=\s*\$?\"[^\"]*\{", False,
     "Unparameterised ADO.NET query."),
    ("cs.deser", "deser", "unsafe .NET serializer", 9, CS,
     r"BinaryFormatter|NetDataContractSerializer|LosFormatter|ObjectStateFormatter|SoapFormatter|JavaScriptSerializer|TypeNameHandling\s*=\s*TypeNameHandling\.(?:All|Objects|Auto)", False,
     "Known RCE deserialisation surfaces."),
    ("cs.cmd", "cmd", "Process.Start", 7, CS, r"Process\.Start\s*\(", False,
     "Command execution."),
    ("cs.path", "path", "Path.Combine with request data", 7, CS,
     r"Path\.Combine\s*\((?:[^)]|\n){0,80}(?:Request|query|fileName)", False,
     "Traversal candidate."),
    ("cs.xxe", "xxe", "XmlDocument / DtdProcessing", 6, CS,
     r"XmlDocument|XmlTextReader|DtdProcessing\.(?:Parse|Ignore)|XmlResolver", False,
     "XXE unless DTD processing is prohibited."),
    ("cs.tls_off", "tls", "certificate callback returns true", 8, CS,
     r"ServerCertificateValidationCallback\s*\+?=|ServerCertificateCustomValidationCallback", False,
     "Certificate validation replaced."),
    ("cs.authz", "authz", "Authorize / AllowAnonymous", 5, CS,
     r"\[Authorize|\[AllowAnonymous\]|\[HttpPost\]|\[FromBody\]", False,
     "Controller access control worth reviewing per action."),

    # ---- shell / ci
    ("sh.eval", "cmd", "eval in shell", 7, SH, r"\beval\s+[\"'$]|\beval\s+\$", False,
     "Re-evaluates a built string as a command."),
    ("sh.var_cmd", "cmd", "unquoted variable in command", 5, SH,
     r"\b(?:rm|mv|cp|chmod|chown|curl|wget|tar|ssh|docker)\s+[^|\n]{0,60}\$\{?[A-Za-z_]", False,
     "Word splitting / injection if the variable holds input."),
    ("sh.pipe_shell", "supply", "curl | sh", 7, SH,
     r"(?:curl|wget)[^|\n]{0,120}\|\s*(?:sudo\s+)?(?:ba|z|d)?sh", False,
     "Remote code executed straight from the network."),
    ("sh.tls_off", "tls", "insecure download flag", 6, SH,
     r"curl\s[^\n]{0,80}(?:\s-k\b|--insecure)|wget\s[^\n]{0,80}--no-check-certificate", False,
     "Download without certificate validation."),

    # ---- secrets (any language)
    ("sec.aws", "secret", "AWS access key id", 9, (),
     r"\b(?:AKIA|ASIA|ABIA|ACCA)[0-9A-Z]{16}\b", False,
     "Live AWS key format."),
    ("sec.privkey", "secret", "private key block", 9, (),
     r"-----BEGIN\s+(?:RSA|EC|DSA|OPENSSH|PGP|ENCRYPTED)?\s*PRIVATE KEY", False,
     "Embedded private key."),
    ("sec.provider_token", "secret", "provider token literal", 9, (),
     r"\b(?:xox[baprs]-[0-9A-Za-z-]{10,}|gh[pousr]_[0-9A-Za-z]{20,}|glpat-[0-9A-Za-z_-]{16,}|sk_live_[0-9A-Za-z]{16,}|rk_live_[0-9A-Za-z]{16,}|AIza[0-9A-Za-z_-]{30,}|SG\.[0-9A-Za-z_-]{16,}\.[0-9A-Za-z_-]{16,})", False,
     "Vendor-specific credential pattern."),
    ("sec.assign", "secret", "credential assigned a literal", 7, (),
     r"(?:api[_-]?key|apikey|secret(?:_key)?|password|passwd|pwd|token|credential|private[_-]?key|access[_-]?key|auth[_-]?key|client[_-]?secret)\s*(?:=|:|=>)\s*[\"'][A-Za-z0-9_\-/+=.]{12,}[\"']", True,
     "Hardcoded credential candidate (check it is not a placeholder)."),
    ("sec.basic_url", "secret", "credentials inside URL", 8, (),
     r"[a-z][a-z0-9+.-]*://[A-Za-z0-9._%-]+:[^@\s/\"'<>]{4,}@", False,
     "User:password embedded in a connection string."),
    ("sec.jwt_literal", "secret", "JWT literal in source", 6, (),
     r"\beyJ[A-Za-z0-9_-]{8,}\.[A-Za-z0-9_-]{8,}\.[A-Za-z0-9_-]{6,}", False,
     "Baked-in token, may still be valid."),

    # ---- config / infra / ci
    ("cfg.k8s_priv", "config", "privileged container settings", 6, CFG,
     r"privileged:\s*true|hostNetwork:\s*true|hostPID:\s*true|allowPrivilegeEscalation:\s*true|runAsUser:\s*0", False,
     "Container escape surface."),
    ("cfg.open_net", "config", "network open to 0.0.0.0/0", 6, CFG,
     r"0\.0\.0\.0/0|\"::/0\"|source_ranges\s*=\s*\[\s*\"0\.0\.0\.0/0", False,
     "Unrestricted ingress."),
    ("cfg.docker_root", "config", "container runs as root / remote ADD", 5, ("dockerfile",),
     r"^\s*USER\s+root|--privileged|^\s*ADD\s+https?://", False,
     "Privileged runtime or unverified remote fetch at build time."),
    ("cfg.debug", "config", "debug / dev mode flag", 4, CFG,
     r"(?:debug|DEBUG)\s*[:=]\s*(?:true|True|1|\"true\")|APP_ENV\s*[:=]\s*(?:dev|local)", False,
     "Verbose errors and relaxed checks."),
    ("cfg.ci_injection", "supply", "CI uses untrusted event data", 8, CFG,
     r"pull_request_target|workflow_run|\$\{\{\s*github\.event\.(?:issue|comment|pull_request|head_commit)\.[a-z_]+", False,
     "Attacker-controlled text interpolated into a privileged CI job."),
    ("cfg.ci_secret_echo", "supply", "secret used in run step", 5, CFG,
     r"\$\{\{\s*secrets\.[A-Za-z0-9_]+\s*\}\}", False,
     "Secret exposure path; check it is not printed or passed to third-party actions."),
    ("cfg.install_hook", "supply", "package install hook", 5, ("json",),
     r"\"(?:pre|post)?install\"\s*:|\"prepare\"\s*:", False,
     "Runs on dependency install; supply-chain relevant."),

    # ---- developer self-reported weakness (any language)
    ("gen.security_todo", "suppress", "TODO/FIXME about security", 5, (),
     r"(?:TODO|FIXME|XXX|HACK|BUG)\b[^\n]{0,80}(?:secur|auth|sanitiz|escap|inject|vuln|unsafe|exploit|permission|validate|temporar|workaround|bypass)", True,
     "The author already flagged this spot as weak."),
    ("gen.suppressed", "suppress", "security linter suppressed", 5, (),
     r"#\s*nosec|noqa:\s*S\d|eslint-disable[^\n]{0,40}(?:security|no-eval|no-unsafe)|@SuppressWarnings\s*\(\s*\"?(?:squid|security)|//\s*gosec:disable|#\s*type:\s*ignore\[misc\]", True,
     "A scanner complained here and was silenced."),
    ("gen.trust_comment", "suppress", "comment assumes trusted input", 3, (),
     r"(?:trusted input|already validated|no validation needed|assume(?:d)? safe|sanitized elsewhere|not user (?:controlled|facing))", True,
     "Assumption to verify; assumptions rot."),
]

# --------------------------------------------------- untrusted input sources

SOURCES: list[tuple] = [
    ("src.py.flask", PY, r"request\.(?:args|form|json|data|files|values|cookies|headers|get_json)"),
    ("src.py.django", PY, r"request\.(?:GET|POST|FILES|COOKIES|META|body|headers)"),
    ("src.py.fastapi", PY, r"(?:Query|Path|Body|Form|File|Header|Cookie)\s*\(|:\s*(?:Request|UploadFile)\b"),
    ("src.py.cli", PY, r"sys\.argv|argparse|click\.(?:option|argument)|typer\."),
    ("src.js.express", JS, r"req\.(?:body|query|params|headers|cookies|files|get\s*\()"),
    ("src.js.next", JS, r"(?:searchParams|useParams|getServerSideProps|NextRequest|context\.query)"),
    ("src.js.browser", JS, r"(?:location\.(?:search|hash|href)|document\.referrer|window\.name|postMessage|URLSearchParams)"),
    ("src.js.lambda", JS, r"event\.(?:body|queryStringParameters|pathParameters|headers)"),
    ("src.php", PHP, r"\$_(?:GET|POST|REQUEST|COOKIE|FILES|SERVER|ENV)|php://input|getallheaders"),
    ("src.java", JAVA, r"(?:request\.getParameter|getHeader|getInputStream|@RequestParam|@PathVariable|@RequestBody|getQueryString)"),
    ("src.go", GO, r"(?:r\.(?:FormValue|PostFormValue|URL\.Query|Body|Header\.Get)|mux\.Vars|c\.(?:Param|Query|PostForm|ShouldBind))"),
    ("src.ruby", RB, r"\bparams\[|request\.(?:body|headers|env|query_parameters)|cookies\["),
    ("src.cs", CS, r"Request\.(?:Query|Form|Body|Headers|Cookies|QueryString|Params)|\[FromQuery\]|\[FromBody\]"),
    ("src.c", CFAM, r"(?:argv\[|getenv\s*\(|recv\s*\(|read\s*\(\s*0|fgets\s*\(\s*\w+\s*,\s*\w+\s*,\s*stdin)"),
    ("src.graphql", (), r"(?:resolve\s*[:(]|Resolver|@Mutation|@Query)\s*[\(\{]"),
    ("src.webhook", (), r"(?:webhook|callback_url|X-Hub-Signature|stripe-signature|X-Signature)"),
]

# --------------------------------------------------------------- entrypoints

ENTRYPOINTS: list[tuple] = [
    ("ep.flask", "HTTP route", PY, r"@(?:app|bp|blueprint|\w+)\.(?:route|get|post|put|patch|delete)\s*\("),
    ("ep.fastapi", "HTTP route", PY, r"@(?:app|router|api)\.(?:get|post|put|patch|delete|websocket)\s*\("),
    ("ep.django_urls", "URL map", PY, r"(?:urlpatterns\s*=|\bpath\s*\(\s*[\"']|\bre_path\s*\(|\burl\s*\(\s*r?[\"'])"),
    ("ep.drf", "API view", PY, r"(?:APIView|ViewSet|ModelViewSet|GenericAPIView|@api_view)"),
    ("ep.celery", "async task", PY, r"@(?:shared_task|celery\.task|app\.task)"),
    ("ep.express", "HTTP route", JS, r"(?:app|router|server)\.(?:get|post|put|patch|delete|all|use)\s*\(\s*[\"'`/]"),
    ("ep.nest", "controller", JS, r"@(?:Controller|Get|Post|Put|Patch|Delete|Injectable)\s*\("),
    ("ep.next_api", "API handler", JS, r"export\s+(?:default\s+)?(?:async\s+)?function\s+(?:handler|GET|POST|PUT|DELETE)|export\s+const\s+(?:GET|POST|PUT|DELETE)"),
    ("ep.lambda", "serverless handler", (), r"(?:exports\.handler|def\s+(?:lambda_)?handler\s*\(\s*event|func\s+HandleRequest)"),
    ("ep.spring", "HTTP route", JAVA, r"@(?:RestController|Controller|RequestMapping|GetMapping|PostMapping|PutMapping|DeleteMapping|PatchMapping)"),
    ("ep.jaxrs", "HTTP route", JAVA, r"@(?:Path|GET|POST|PUT|DELETE)\b"),
    ("ep.go_http", "HTTP route", GO, r"(?:http\.HandleFunc|mux\.(?:HandleFunc|Handle)|\.(?:GET|POST|PUT|DELETE|PATCH)\s*\(\s*\"|router\.(?:Group|Handle))"),
    ("ep.rails", "route map", RB, r"(?:Rails\.application\.routes\.draw|resources\s+:|\bget\s+[\"']|\bpost\s+[\"'])"),
    ("ep.php_front", "web entry", PHP, r"(?:\$_SERVER\[[\"']REQUEST_URI|Route::(?:get|post|put|delete)|->group\s*\()"),
    ("ep.aspnet", "HTTP route", CS, r"\[(?:HttpGet|HttpPost|HttpPut|HttpDelete|Route)\s*\(|MapControllers|MapGet\s*\("),
    ("ep.grpc", "RPC service", (), r"(?:service\s+\w+\s*\{|grpc\.(?:NewServer|ServiceDesc)|ServerInterceptor)"),
    ("ep.graphql_schema", "GraphQL schema", (), r"(?:type\s+(?:Query|Mutation)\s*\{|buildSchema|makeExecutableSchema|@ObjectType)"),
    ("ep.socket", "websocket/socket", (), r"(?:socket\.on\s*\(|io\.on\s*\(|WebSocketServer|websocket\.serve|@sio\.event)"),
    ("ep.cli", "CLI entry", (), r"(?:if\s+__name__\s*==\s*[\"']__main__|func\s+main\s*\(\s*\)|public\s+static\s+void\s+main|#!/(?:usr/)?bin/(?:env\s+)?(?:ba)?sh)"),
    ("ep.cron", "scheduled job", (), r"(?:cron|schedule\.(?:every|run_pending)|@Scheduled|setInterval\s*\(\s*\w+\s*,\s*\d{4,})"),
]

# ---------------------------------------------------- path / filename signals

PATH_SIGNALS: list[tuple] = [
    (r"(?:^|/)(?:auth|authn|authentication|login|signin|sign_in|sso|oauth|oidc|saml|session|jwt|token|password|passwd|credential|mfa|2fa|otp)", 9, "authentication surface"),
    (r"(?:^|/)(?:admin|administrator|superuser|internal|staff|backoffice|management|console|dashboard)", 8, "privileged area"),
    (r"(?:^|/)(?:payment|billing|invoice|charge|checkout|order|refund|wallet|balance|transfer|payout|subscription|coupon|voucher|price)", 8, "money handling"),
    (r"(?:^|/)(?:permission|authorization|authz|acl|rbac|policy|policies|guard|middleware|interceptor|filter)", 7, "access-control logic"),
    (r"(?:^|/)(?:upload|uploads|file|files|attachment|media|storage|import|export|download|avatar|image)", 6, "file handling"),
    (r"(?:^|/)(?:api|apis|controller|controllers|handler|handlers|route|routes|routers|endpoint|endpoints|view|views|resolver|resolvers|rpc|graphql|webhook|hooks|callback)", 6, "request entry layer"),
    (r"(?:^|/)(?:crypt|crypto|cipher|encrypt|decrypt|hash|signature|verify|secret|secrets|vault|kms|hmac|jwks|keystore)|(?:^|/)(?:sign|key|keys|keyring)(?![a-z])", 7, "crypto / secret handling"),
    (r"(?:^|/)(?:serial|serializer|deserial|pickle|marshal|unmarshal|decode|decoder|parse|parser|codec)", 6, "parsing / deserialisation"),
    (r"(?:^|/)(?:exec|command|commands|shell|proc|process|spawn|runner|task|worker|job|jobs|queue)", 6, "execution / worker path"),
    (r"(?:^|/)(?:proxy|gateway|fetch|http|client|request|requests|curl|outbound|integration|connector)", 5, "outbound request layer"),
    (r"(?:^|/)(?:user|users|account|accounts|profile|tenant|org|organization|team|member|invite|role|roles)", 5, "identity objects (IDOR)"),
    (r"(?:^|/)(?:sql|query|queries|database|repository|repositories|dao|orm|model|models|entity|migration)|(?:^|/)(?:db|ddl)(?![a-z])", 4, "data layer"),
    (r"(?:^|/)(?:sanitiz|sanitis|escape|validator|validation|validate|filter|whitelist|allowlist|blocklist|blacklist)", 5, "defence code (bypass target)"),
    (r"(?:^|/)(?:template|templates|render|renderer|email|mail|notification|sms|report|pdf|invoice)", 4, "templating / rendering"),
    (r"(?:^|/)(?:config|configuration|settings|setup|secrets?\.|\.env|deploy|infra|terraform|helm|k8s|kubernetes|docker)|(?:^|/)env(?![a-z])", 4, "configuration / infra"),
    (r"(?:^|/)(?:net|socket|server|listener|protocol|packet|frame|codec|websocket|grpc|tcp|udp)", 5, "network protocol code"),
    (r"(?:^|/)(?:mobile|android|ios|native|bridge|webview|deeplink|intent|scheme)", 5, "mobile bridge"),
    (r"(?:^|/)(?:legacy|deprecated|obsolete|old|backup|bak|tmp|temp|copy|draft|wip|experimental|poc|todo)(?![a-z])", 6, "neglected code"),
    (r"(?:^|/)(?:extension|plugin|addon|content[_-]?script|background|manifest\.json|service[_-]?worker)", 5, "browser extension surface"),
]

NEGATIVE_PATH_SIGNALS: list[tuple] = [
    (r"(?:^|/)(?:locale|locales|i18n|l10n|translations?|lang)(?:/|$)", 0.35, "localisation data"),
    (r"(?:^|/)(?:docs?|documentation|examples?|samples?|demos?|tutorials?)(?:/|$)", 0.45, "documentation"),
    (r"(?:^|/)(?:changelog|license|licence|contributing|readme|authors|notice|codeowners)", 0.25, "project metadata"),
    (r"(?:^|/)(?:assets?|static|public|img|images|fonts?|icons?|css|styles?|scss)(?:/|$)", 0.5, "static assets"),
    (r"(?:^|/)(?:\.github/ISSUE_TEMPLATE|\.gitignore|\.editorconfig|\.prettierrc)", 0.3, "repo hygiene files"),
]


def _compile(pattern: str, ci: bool):
    flags = re.MULTILINE
    if ci:
        flags |= re.IGNORECASE
    try:
        return re.compile(pattern, flags)
    except re.error as exc:  # a broken rule must never break a scan
        return None


COMPILED_RULES = []
for _id, _cat, _title, _w, _langs, _pat, _ci, _why in RULES:
    rx = _compile(_pat, _ci)
    if rx is not None:
        COMPILED_RULES.append({
            "id": _id, "cat": _cat, "title": _title, "weight": _w,
            "langs": set(_langs), "rx": rx, "why": _why,
            "cwe": CATEGORIES.get(_cat, {}).get("cwe", ""),
        })

COMPILED_SOURCES = [
    {"id": i, "langs": set(l), "rx": _compile(p, False)}
    for i, l, p in SOURCES if _compile(p, False)
]
COMPILED_ENTRYPOINTS = [
    {"id": i, "kind": k, "langs": set(l), "rx": _compile(p, False)}
    for i, k, l, p in ENTRYPOINTS if _compile(p, False)
]
COMPILED_PATH_SIGNALS = [(re.compile(p, re.I), w, label) for p, w, label in PATH_SIGNALS]
COMPILED_NEG_SIGNALS = [(re.compile(p, re.I), f, label) for p, f, label in NEGATIVE_PATH_SIGNALS]


def rule_count() -> dict:
    return {
        "sinks": len(COMPILED_RULES),
        "sources": len(COMPILED_SOURCES),
        "entrypoints": len(COMPILED_ENTRYPOINTS),
        "path_signals": len(COMPILED_PATH_SIGNALS),
        "categories": len(CATEGORIES),
    }
