"""Download the console's typefaces as local woff2 and emit static/fonts/fonts.css.

Self-hosted on purpose: the app then works offline, loads without a round trip to a CDN, and
does not tell Google what you are looking at. Re-run after changing FAMILIES.

    python tools/fetch_fonts.py
"""
from __future__ import annotations

import re
import sys
import urllib.request
from pathlib import Path

ROOT = Path(__file__).resolve().parent.parent
OUT = ROOT / "repoxray" / "static" / "fonts"

# A modern UA is required or the API serves ttf instead of woff2.
UA = ("Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) "
      "Chrome/122.0.0.0 Safari/537.36")

FAMILIES = [
    # (label, css2 query, local file stem)
    ("Bodoni Moda",   "Bodoni+Moda:ital,wght@0,400..700;1,400..600", "bodoni-moda"),
    ("Martian Mono",  "Martian+Mono:wght@300..700",                  "martian-mono"),
    ("Archivo",       "Archivo:ital,wght@0,400..700;1,400..600",     "archivo"),
    ("JetBrains Mono", "JetBrains+Mono:ital,wght@0,400..700;1,400..600", "jetbrains-mono"),
]

WANT_SUBSETS = ("latin",)   # keep the payload small; drop latin-ext, cyrillic, greek


def fetch(url: str, binary: bool = False):
    req = urllib.request.Request(url, headers={"User-Agent": UA})
    with urllib.request.urlopen(req, timeout=60) as r:
        data = r.read()
    return data if binary else data.decode("utf-8")


def parse_faces(css: str) -> list:
    """Pull (subset, style, weight, url) out of the API response."""
    faces = []
    subset = "unknown"
    for block in re.split(r"(?=/\*\s*[a-z-]+\s*\*/)", css):
        label = re.match(r"/\*\s*([a-z-]+)\s*\*/", block.strip())
        if label:
            subset = label.group(1)
        for face in re.findall(r"@font-face\s*\{(.*?)\}", block, re.S):
            url = re.search(r"url\((https://[^)]+\.woff2)\)", face)
            if not url:
                continue
            style = re.search(r"font-style:\s*([a-z]+)", face)
            weight = re.search(r"font-weight:\s*([\d\s]+)", face)
            faces.append({
                "subset": subset,
                "style": (style.group(1) if style else "normal"),
                "weight": (weight.group(1).strip() if weight else "400"),
                "url": url.group(1),
            })
    return faces


def main() -> int:
    OUT.mkdir(parents=True, exist_ok=True)
    css_out = ["/* Generated by tools/fetch_fonts.py - do not edit by hand. */", ""]
    total = 0

    for label, query, stem in FAMILIES:
        api = "https://fonts.googleapis.com/css2?family=" + query + "&display=swap"
        print("fetching " + label + " ...")
        try:
            css = fetch(api)
        except Exception as exc:
            print("  FAILED: " + type(exc).__name__ + ": " + str(exc)[:120])
            return 1

        faces = [f for f in parse_faces(css) if f["subset"] in WANT_SUBSETS]
        if not faces:
            print("  no matching subset in response")
            return 1

        for face in faces:
            suffix = "-italic" if face["style"] == "italic" else ""
            name = stem + suffix + ".woff2"
            blob = fetch(face["url"], binary=True)
            (OUT / name).write_bytes(blob)
            total += len(blob)
            print("  " + name + "  " + str(round(len(blob) / 1024)) + "KB  weight " + face["weight"])
            css_out += [
                "@font-face {",
                '  font-family: "' + label + '";',
                "  font-style: " + face["style"] + ";",
                "  font-weight: " + face["weight"] + ";",
                "  font-display: swap;",
                '  src: url("./' + name + '") format("woff2");',
                "}",
                "",
            ]

    (OUT / "fonts.css").write_text("\n".join(css_out), encoding="utf-8")
    print("\nwrote " + str(OUT / "fonts.css") + "  (" + str(round(total / 1024)) + "KB of fonts)")
    return 0


if __name__ == "__main__":
    sys.exit(main())
